#print("vinay welcome to relaity world")
#print("to meet better half")
print("kavya","bhavya","ramya","boonie")
#print("hi vinay")
#print("welcome to my world")
#print("vinay","is missing you","boonie deeply")
#print("vinay","is missing you","boonie deeply",sep='   ',end=" ")
#print("butiamalwayswithyou")